server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dreevo/config-repo
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
  application:
    name: config-service